KEYWORDS = {
    'class': None,
    'constructor': None,
    'function': None,
    'method': None,
    'field': None,
    'static': None,
    'var': None,
    'int': None,
    'char': None,
    'boolean': None,
    'void': None,
    'true': None,
    'false': None,
    'null': None,
    'this': None,
    'let': None,
    'do': None,
    'if': None,
    'else': None,
    'while': None,
    'return': None
}

SYMBOLS = {
    '(': None,
    ')': None,
    '{': None,
    '}': None,
    '[': None,
    ']': None,
    '.': None,
    ',': None,
    ';': None,
    '+': None,
    '-': None,
    '*': None,
    '/': None,
    '&': None,
    '|': None,
    '<': None,
    '>': None,
    '=': None,
    '~': None
}
