import tokens as T

KEYWORDS_AND_SYMBOLS = {
    'class': T.KeywordToken('class'),
    #'constructor': None,
    #'function': None,
    #'method': None,
    #'field': None,
    #'static': None,
    #'var': None,
    #'int': None,
    #'char': None,
    #'boolean': None,
    #'void': None,
    #'true': None,
    #'false': None,
    #'null': None,
    #'this': None,
    #'let': None,
    #'do': None,
    #'if': None,
    #'else': None,
    #'while': None,
    #'return': None,
    #'(': None,
    #')': None,
    #'{': None,
    #'}': None,
    #'[': None,
    #']': None,
    #'.': None,
    #',': None,
    #';': None,
    #'+': None,
    #'-': None,
    #'*': None,
    #'/': None,
    #'&': None,
    #'|': None,
    #'<': None,
    #'>': None,
    #'=': None,
    #'~': None
}

def get_token(identifier):
    return KEYWORDS_AND_SYMBOLS.get(identifier, T.BaseToken(identifier))
